# docker-compose.dev.yml
version: '3'

services:
  app:
    container_name: mbl-cadastro
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - .env
    # Set environment variables directly in the docker-compose file
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
  db:
    image: postgres:16
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  pgdata: {}